---

- name: Test if {{ csi_namespace }} namespace already exists
  ansible.builtin.command: kubectl get ns
  register: namespace_test
  changed_when: false

- name: create {{ csi_namespace }} namespace
  ansible.builtin.command: kubectl create ns {{ csi_namespace }}
  when: "'nebulon' not in namespace_test.stdout"

- name: Create Nebulon secret file
  ansible.builtin.command:
    cmd: |
      cat <<EOF | tee /tmp/nebulonsecret.yaml
      apiVersion: v1
      kind: Secret
      metadata:
        name: nebulon-credentials
        namespace: "{{ csi_namespace }}"
      type: Opaque
      stringData:
          api_endpoint: "https://ucapi.nebcloud.nebuloninc.com"
          username: "{{ neb_username }}"
          password: "{{ neb_password }}"
      EOF
  tags: namespace

- name: Apply Nebulon secret file
  ansible.builtin.command: kubectl apply -f /tmp/nebulonsecret.yaml
  when: "'nebulon' not in namespace_test.stdout"
  tags: namespace

- name: Test if CRDs are already loaded
  ansible.builtin.command: kubectl get crd | grep -o volumesnapshotclasses
  register: crd
  changed_when: false
  failed_when: "crd.rc == 2"

- name: Install K8s CRDs for snapshot support
  ansible.builtin.command: "{{ crd_url }}{{ item }}"
  with_items:
    - "client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml"
    - "client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml"
    - "client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml"
    - "deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml"
    - "deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml"
  when: "'volumesnapshotclasses' not in crd.stdout"

- name: Add Nebulon Helm repository
  ansible.builtin.command: helm repo add nebulon https://nebulon.github.io/helm-charts

- name: Check if Nebulon CSI driver already loaded
  ansible.builtin.command: helm list -n {{ csi_namespace }}
  register: helm
  changed_when: false
  tags: helm

# TODO: Make the when: conditional check for the correct namespace
# This is breaking as of May 2022 with:
# "Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest:
# resource mapping not found for name: "nebulon-snap" namespace: "" from "":
# no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1beta1" ensure CRDs are installed first

# - name: Install Nebulon CSI driver
#   ansible.builtin.shell:
#     cmd: |
#       helm install csi-nebulon nebulon/csi-nebulon --create-namespace -n {{ csi_namespace }} --set snapshotclass.enabled=true
#   when: "'nebulon' not in helm.stdout"
#   tags: csi, helm

# Install the Nebulon CSI driver without snapshot support enabled
- name: Install Nebulon CSI driver
  ansible.builtin.command:
    cmd: |
      helm install csi-nebulon nebulon/csi-nebulon --create-namespace -n {{ csi_namespace }}
  when: "'nebulon' not in helm.stdout"
